import IISAvtomatizaciya_zakupok5ПланЗакупокEController from '../i-i-s-avtomatizaciya-zakupok5-план-закупок-e';

var IISAvtomatizaciya_zakupok5ПланЗакупокENewController = IISAvtomatizaciya_zakupok5ПланЗакупокEController;
export default IISAvtomatizaciya_zakupok5ПланЗакупокENewController;
