import IISAvtomatizaciya_zakupok5ОрганизацииEController from '../i-i-s-avtomatizaciya-zakupok5-организации-e';

var IISAvtomatizaciya_zakupok5ОрганизацииENewController = IISAvtomatizaciya_zakupok5ОрганизацииEController;
export default IISAvtomatizaciya_zakupok5ОрганизацииENewController;
