//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_zakupok5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отчет о закупках.
    /// </summary>
    // *** Start programmer edit section *** (ОтчеЗакупках CustomAttributes)

    // *** End programmer edit section *** (ОтчеЗакупках CustomAttributes)
    [AutoAltered()]
    [Caption("Отчет о закупках")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчетОЗакупкахE", new string[] {
            "Номер as \'Номер\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Организации as \'Организации\'",
            "Организации.Организация as \'Организация\'",
            "Склады as \'Склады\'",
            "Контрагенты as \'Контрагенты\'",
            "Контрагенты.Контрагент as \'Контрагент\'",
            "СостояниеОплаты as \'Состояние оплаты\'",
            "Склады.Склад as \'Склад\'",
            "СостОтгрузки as \'Сост отгрузки\'",
            "СуммаВклНДС as \'Сумма вкл НДС\'",
            "СуммаДокумента as \'Сумма документа\'"})]
    [View("ОтчетОЗакупкахL", new string[] {
            "Номер as \'Номер\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Организации.Организация as \'Организация\'",
            "Склады.Склад as \'Склад\'",
            "Контрагенты.Контрагент as \'Контрагент\'",
            "СуммаВклНДС as \'Сумма вкл НДС\'",
            "СуммаДокумента as \'Сумма документа\'",
            "СостояниеОплаты as \'Состояние оплаты\'",
            "СостОтгрузки as \'Сост отгрузки\'"})]
    public class ОтчеЗакупках : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private System.DateTime fДатаНачала = System.DateTime.Now;
        
        private System.DateTime fДатаОкончания;
        
        private IIS.Avtomatizaciya_zakupok5.СостОплаты fСостояниеОплаты;
        
        private bool fСуммаВклНДС;
        
        private IIS.Avtomatizaciya_zakupok5.СостПоставок fСостОтгрузки;
        
        private int fСуммаДокумента;
        
        private IIS.Avtomatizaciya_zakupok5.Склады fСклады;
        
        private IIS.Avtomatizaciya_zakupok5.Контрагенты fКонтрагенты;
        
        private IIS.Avtomatizaciya_zakupok5.Организации fОрганизации;
        
        private IIS.Avtomatizaciya_zakupok5.DetailArrayOfТЧЗаказ fТЧЗаказ;
        
        private IIS.Avtomatizaciya_zakupok5.DetailArrayOfТЧОтчет fТЧОтчет;
        
        // *** Start programmer edit section *** (ОтчеЗакупках CustomMembers)

        // *** End programmer edit section *** (ОтчеЗакупках CustomMembers)

        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (ОтчеЗакупках.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (ОтчеЗакупках.ДатаНачала CustomAttributes)
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.ДатаНачала Get start)

                // *** End programmer edit section *** (ОтчеЗакупках.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (ОтчеЗакупках.ДатаНачала Get end)

                // *** End programmer edit section *** (ОтчеЗакупках.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.ДатаНачала Set start)

                // *** End programmer edit section *** (ОтчеЗакупках.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (ОтчеЗакупках.ДатаНачала Set end)

                // *** End programmer edit section *** (ОтчеЗакупках.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончания.
        /// </summary>
        // *** Start programmer edit section *** (ОтчеЗакупках.ДатаОкончания CustomAttributes)

        // *** End programmer edit section *** (ОтчеЗакупках.ДатаОкончания CustomAttributes)
        public virtual System.DateTime ДатаОкончания
        {
            get
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.ДатаОкончания Get start)

                // *** End programmer edit section *** (ОтчеЗакупках.ДатаОкончания Get start)
                System.DateTime result = this.fДатаОкончания;
                // *** Start programmer edit section *** (ОтчеЗакупках.ДатаОкончания Get end)

                // *** End programmer edit section *** (ОтчеЗакупках.ДатаОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.ДатаОкончания Set start)

                // *** End programmer edit section *** (ОтчеЗакупках.ДатаОкончания Set start)
                this.fДатаОкончания = value;
                // *** Start programmer edit section *** (ОтчеЗакупках.ДатаОкончания Set end)

                // *** End programmer edit section *** (ОтчеЗакупках.ДатаОкончания Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ОтчеЗакупках.Номер CustomAttributes)

        // *** End programmer edit section *** (ОтчеЗакупках.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.Номер Get start)

                // *** End programmer edit section *** (ОтчеЗакупках.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ОтчеЗакупках.Номер Get end)

                // *** End programmer edit section *** (ОтчеЗакупках.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.Номер Set start)

                // *** End programmer edit section *** (ОтчеЗакупках.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ОтчеЗакупках.Номер Set end)

                // *** End programmer edit section *** (ОтчеЗакупках.Номер Set end)
            }
        }
        
        /// <summary>
        /// СостОтгрузки.
        /// </summary>
        // *** Start programmer edit section *** (ОтчеЗакупках.СостОтгрузки CustomAttributes)

        // *** End programmer edit section *** (ОтчеЗакупках.СостОтгрузки CustomAttributes)
        public virtual IIS.Avtomatizaciya_zakupok5.СостПоставок СостОтгрузки
        {
            get
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.СостОтгрузки Get start)

                // *** End programmer edit section *** (ОтчеЗакупках.СостОтгрузки Get start)
                IIS.Avtomatizaciya_zakupok5.СостПоставок result = this.fСостОтгрузки;
                // *** Start programmer edit section *** (ОтчеЗакупках.СостОтгрузки Get end)

                // *** End programmer edit section *** (ОтчеЗакупках.СостОтгрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.СостОтгрузки Set start)

                // *** End programmer edit section *** (ОтчеЗакупках.СостОтгрузки Set start)
                this.fСостОтгрузки = value;
                // *** Start programmer edit section *** (ОтчеЗакупках.СостОтгрузки Set end)

                // *** End programmer edit section *** (ОтчеЗакупках.СостОтгрузки Set end)
            }
        }
        
        /// <summary>
        /// СостояниеОплаты.
        /// </summary>
        // *** Start programmer edit section *** (ОтчеЗакупках.СостояниеОплаты CustomAttributes)

        // *** End programmer edit section *** (ОтчеЗакупках.СостояниеОплаты CustomAttributes)
        public virtual IIS.Avtomatizaciya_zakupok5.СостОплаты СостояниеОплаты
        {
            get
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.СостояниеОплаты Get start)

                // *** End programmer edit section *** (ОтчеЗакупках.СостояниеОплаты Get start)
                IIS.Avtomatizaciya_zakupok5.СостОплаты result = this.fСостояниеОплаты;
                // *** Start programmer edit section *** (ОтчеЗакупках.СостояниеОплаты Get end)

                // *** End programmer edit section *** (ОтчеЗакупках.СостояниеОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.СостояниеОплаты Set start)

                // *** End programmer edit section *** (ОтчеЗакупках.СостояниеОплаты Set start)
                this.fСостояниеОплаты = value;
                // *** Start programmer edit section *** (ОтчеЗакупках.СостояниеОплаты Set end)

                // *** End programmer edit section *** (ОтчеЗакупках.СостояниеОплаты Set end)
            }
        }
        
        /// <summary>
        /// СуммаВклНДС.
        /// </summary>
        // *** Start programmer edit section *** (ОтчеЗакупках.СуммаВклНДС CustomAttributes)

        // *** End programmer edit section *** (ОтчеЗакупках.СуммаВклНДС CustomAttributes)
        public virtual bool СуммаВклНДС
        {
            get
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.СуммаВклНДС Get start)

                // *** End programmer edit section *** (ОтчеЗакупках.СуммаВклНДС Get start)
                bool result = this.fСуммаВклНДС;
                // *** Start programmer edit section *** (ОтчеЗакупках.СуммаВклНДС Get end)

                // *** End programmer edit section *** (ОтчеЗакупках.СуммаВклНДС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.СуммаВклНДС Set start)

                // *** End programmer edit section *** (ОтчеЗакупках.СуммаВклНДС Set start)
                this.fСуммаВклНДС = value;
                // *** Start programmer edit section *** (ОтчеЗакупках.СуммаВклНДС Set end)

                // *** End programmer edit section *** (ОтчеЗакупках.СуммаВклНДС Set end)
            }
        }
        
        /// <summary>
        /// СуммаДокумента.
        /// </summary>
        // *** Start programmer edit section *** (ОтчеЗакупках.СуммаДокумента CustomAttributes)

        // *** End programmer edit section *** (ОтчеЗакупках.СуммаДокумента CustomAttributes)
        public virtual int СуммаДокумента
        {
            get
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.СуммаДокумента Get start)

                // *** End programmer edit section *** (ОтчеЗакупках.СуммаДокумента Get start)
                int result = this.fСуммаДокумента;
                // *** Start programmer edit section *** (ОтчеЗакупках.СуммаДокумента Get end)

                // *** End programmer edit section *** (ОтчеЗакупках.СуммаДокумента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.СуммаДокумента Set start)

                // *** End programmer edit section *** (ОтчеЗакупках.СуммаДокумента Set start)
                this.fСуммаДокумента = value;
                // *** Start programmer edit section *** (ОтчеЗакупках.СуммаДокумента Set end)

                // *** End programmer edit section *** (ОтчеЗакупках.СуммаДокумента Set end)
            }
        }
        
        /// <summary>
        /// Отчет о закупках.
        /// </summary>
        // *** Start programmer edit section *** (ОтчеЗакупках.Контрагенты CustomAttributes)

        // *** End programmer edit section *** (ОтчеЗакупках.Контрагенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Контрагенты"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_zakupok5.Контрагенты Контрагенты
        {
            get
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.Контрагенты Get start)

                // *** End programmer edit section *** (ОтчеЗакупках.Контрагенты Get start)
                IIS.Avtomatizaciya_zakupok5.Контрагенты result = this.fКонтрагенты;
                // *** Start programmer edit section *** (ОтчеЗакупках.Контрагенты Get end)

                // *** End programmer edit section *** (ОтчеЗакупках.Контрагенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.Контрагенты Set start)

                // *** End programmer edit section *** (ОтчеЗакупках.Контрагенты Set start)
                this.fКонтрагенты = value;
                // *** Start programmer edit section *** (ОтчеЗакупках.Контрагенты Set end)

                // *** End programmer edit section *** (ОтчеЗакупках.Контрагенты Set end)
            }
        }
        
        /// <summary>
        /// Отчет о закупках.
        /// </summary>
        // *** Start programmer edit section *** (ОтчеЗакупках.Организации CustomAttributes)

        // *** End programmer edit section *** (ОтчеЗакупках.Организации CustomAttributes)
        [PropertyStorage(new string[] {
                "Организации"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_zakupok5.Организации Организации
        {
            get
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.Организации Get start)

                // *** End programmer edit section *** (ОтчеЗакупках.Организации Get start)
                IIS.Avtomatizaciya_zakupok5.Организации result = this.fОрганизации;
                // *** Start programmer edit section *** (ОтчеЗакупках.Организации Get end)

                // *** End programmer edit section *** (ОтчеЗакупках.Организации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.Организации Set start)

                // *** End programmer edit section *** (ОтчеЗакупках.Организации Set start)
                this.fОрганизации = value;
                // *** Start programmer edit section *** (ОтчеЗакупках.Организации Set end)

                // *** End programmer edit section *** (ОтчеЗакупках.Организации Set end)
            }
        }
        
        /// <summary>
        /// Отчет о закупках.
        /// </summary>
        // *** Start programmer edit section *** (ОтчеЗакупках.Склады CustomAttributes)

        // *** End programmer edit section *** (ОтчеЗакупках.Склады CustomAttributes)
        [PropertyStorage(new string[] {
                "Склады"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_zakupok5.Склады Склады
        {
            get
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.Склады Get start)

                // *** End programmer edit section *** (ОтчеЗакупках.Склады Get start)
                IIS.Avtomatizaciya_zakupok5.Склады result = this.fСклады;
                // *** Start programmer edit section *** (ОтчеЗакупках.Склады Get end)

                // *** End programmer edit section *** (ОтчеЗакупках.Склады Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.Склады Set start)

                // *** End programmer edit section *** (ОтчеЗакупках.Склады Set start)
                this.fСклады = value;
                // *** Start programmer edit section *** (ОтчеЗакупках.Склады Set end)

                // *** End programmer edit section *** (ОтчеЗакупках.Склады Set end)
            }
        }
        
        /// <summary>
        /// Отчет о закупках.
        /// </summary>
        // *** Start programmer edit section *** (ОтчеЗакупках.ТЧЗаказ CustomAttributes)

        // *** End programmer edit section *** (ОтчеЗакупках.ТЧЗаказ CustomAttributes)
        public virtual IIS.Avtomatizaciya_zakupok5.DetailArrayOfТЧЗаказ ТЧЗаказ
        {
            get
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.ТЧЗаказ Get start)

                // *** End programmer edit section *** (ОтчеЗакупках.ТЧЗаказ Get start)
                if ((this.fТЧЗаказ == null))
                {
                    this.fТЧЗаказ = new IIS.Avtomatizaciya_zakupok5.DetailArrayOfТЧЗаказ(this);
                }
                IIS.Avtomatizaciya_zakupok5.DetailArrayOfТЧЗаказ result = this.fТЧЗаказ;
                // *** Start programmer edit section *** (ОтчеЗакупках.ТЧЗаказ Get end)

                // *** End programmer edit section *** (ОтчеЗакупках.ТЧЗаказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.ТЧЗаказ Set start)

                // *** End programmer edit section *** (ОтчеЗакупках.ТЧЗаказ Set start)
                this.fТЧЗаказ = value;
                // *** Start programmer edit section *** (ОтчеЗакупках.ТЧЗаказ Set end)

                // *** End programmer edit section *** (ОтчеЗакупках.ТЧЗаказ Set end)
            }
        }
        
        /// <summary>
        /// Отчет о закупках.
        /// </summary>
        // *** Start programmer edit section *** (ОтчеЗакупках.ТЧОтчет CustomAttributes)

        // *** End programmer edit section *** (ОтчеЗакупках.ТЧОтчет CustomAttributes)
        public virtual IIS.Avtomatizaciya_zakupok5.DetailArrayOfТЧОтчет ТЧОтчет
        {
            get
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.ТЧОтчет Get start)

                // *** End programmer edit section *** (ОтчеЗакупках.ТЧОтчет Get start)
                if ((this.fТЧОтчет == null))
                {
                    this.fТЧОтчет = new IIS.Avtomatizaciya_zakupok5.DetailArrayOfТЧОтчет(this);
                }
                IIS.Avtomatizaciya_zakupok5.DetailArrayOfТЧОтчет result = this.fТЧОтчет;
                // *** Start programmer edit section *** (ОтчеЗакупках.ТЧОтчет Get end)

                // *** End programmer edit section *** (ОтчеЗакупках.ТЧОтчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчеЗакупках.ТЧОтчет Set start)

                // *** End programmer edit section *** (ОтчеЗакупках.ТЧОтчет Set start)
                this.fТЧОтчет = value;
                // *** Start programmer edit section *** (ОтчеЗакупках.ТЧОтчет Set end)

                // *** End programmer edit section *** (ОтчеЗакупках.ТЧОтчет Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчетОЗакупкахE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетОЗакупкахE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетОЗакупкахE", typeof(IIS.Avtomatizaciya_zakupok5.ОтчеЗакупках));
                }
            }
            
            /// <summary>
            /// "ОтчетОЗакупкахL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетОЗакупкахL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетОЗакупкахL", typeof(IIS.Avtomatizaciya_zakupok5.ОтчеЗакупках));
                }
            }
        }
    }
}
