//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_zakupok5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТЧОтчет.
    /// </summary>
    // *** Start programmer edit section *** (ТЧОтчет CustomAttributes)

    // *** End programmer edit section *** (ТЧОтчет CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ТЧОтчет : ICSSoft.STORMNET.DataObject
    {
        
        private int fЦена;
        
        private bool fЭтоУслуга;
        
        private int fСуммаНДС;
        
        private int fКоличество;
        
        private int fСумма;
        
        private IIS.Avtomatizaciya_zakupok5.Номенклатура fНоменклатура;
        
        private IIS.Avtomatizaciya_zakupok5.ОтчеЗакупках fОтчеЗакупках;
        
        // *** Start programmer edit section *** (ТЧОтчет CustomMembers)

        // *** End programmer edit section *** (ТЧОтчет CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОтчет.Количество CustomAttributes)

        // *** End programmer edit section *** (ТЧОтчет.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОтчет.Количество Get start)

                // *** End programmer edit section *** (ТЧОтчет.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ТЧОтчет.Количество Get end)

                // *** End programmer edit section *** (ТЧОтчет.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОтчет.Количество Set start)

                // *** End programmer edit section *** (ТЧОтчет.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ТЧОтчет.Количество Set end)

                // *** End programmer edit section *** (ТЧОтчет.Количество Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОтчет.Сумма CustomAttributes)

        // *** End programmer edit section *** (ТЧОтчет.Сумма CustomAttributes)
        public virtual int Сумма
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОтчет.Сумма Get start)

                // *** End programmer edit section *** (ТЧОтчет.Сумма Get start)
                int result = this.fСумма;
                // *** Start programmer edit section *** (ТЧОтчет.Сумма Get end)

                // *** End programmer edit section *** (ТЧОтчет.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОтчет.Сумма Set start)

                // *** End programmer edit section *** (ТЧОтчет.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (ТЧОтчет.Сумма Set end)

                // *** End programmer edit section *** (ТЧОтчет.Сумма Set end)
            }
        }
        
        /// <summary>
        /// СуммаНДС.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОтчет.СуммаНДС CustomAttributes)

        // *** End programmer edit section *** (ТЧОтчет.СуммаНДС CustomAttributes)
        public virtual int СуммаНДС
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОтчет.СуммаНДС Get start)

                // *** End programmer edit section *** (ТЧОтчет.СуммаНДС Get start)
                int result = this.fСуммаНДС;
                // *** Start programmer edit section *** (ТЧОтчет.СуммаНДС Get end)

                // *** End programmer edit section *** (ТЧОтчет.СуммаНДС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОтчет.СуммаНДС Set start)

                // *** End programmer edit section *** (ТЧОтчет.СуммаНДС Set start)
                this.fСуммаНДС = value;
                // *** Start programmer edit section *** (ТЧОтчет.СуммаНДС Set end)

                // *** End programmer edit section *** (ТЧОтчет.СуммаНДС Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОтчет.Цена CustomAttributes)

        // *** End programmer edit section *** (ТЧОтчет.Цена CustomAttributes)
        public virtual int Цена
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОтчет.Цена Get start)

                // *** End programmer edit section *** (ТЧОтчет.Цена Get start)
                int result = this.fЦена;
                // *** Start programmer edit section *** (ТЧОтчет.Цена Get end)

                // *** End programmer edit section *** (ТЧОтчет.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОтчет.Цена Set start)

                // *** End programmer edit section *** (ТЧОтчет.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (ТЧОтчет.Цена Set end)

                // *** End programmer edit section *** (ТЧОтчет.Цена Set end)
            }
        }
        
        /// <summary>
        /// ЭтоУслуга.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОтчет.ЭтоУслуга CustomAttributes)

        // *** End programmer edit section *** (ТЧОтчет.ЭтоУслуга CustomAttributes)
        public virtual bool ЭтоУслуга
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОтчет.ЭтоУслуга Get start)

                // *** End programmer edit section *** (ТЧОтчет.ЭтоУслуга Get start)
                bool result = this.fЭтоУслуга;
                // *** Start programmer edit section *** (ТЧОтчет.ЭтоУслуга Get end)

                // *** End programmer edit section *** (ТЧОтчет.ЭтоУслуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОтчет.ЭтоУслуга Set start)

                // *** End programmer edit section *** (ТЧОтчет.ЭтоУслуга Set start)
                this.fЭтоУслуга = value;
                // *** Start programmer edit section *** (ТЧОтчет.ЭтоУслуга Set end)

                // *** End programmer edit section *** (ТЧОтчет.ЭтоУслуга Set end)
            }
        }
        
        /// <summary>
        /// ТЧОтчет.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОтчет.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (ТЧОтчет.Номенклатура CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенклатура"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_zakupok5.Номенклатура Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОтчет.Номенклатура Get start)

                // *** End programmer edit section *** (ТЧОтчет.Номенклатура Get start)
                IIS.Avtomatizaciya_zakupok5.Номенклатура result = this.fНоменклатура;
                // *** Start programmer edit section *** (ТЧОтчет.Номенклатура Get end)

                // *** End programmer edit section *** (ТЧОтчет.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОтчет.Номенклатура Set start)

                // *** End programmer edit section *** (ТЧОтчет.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (ТЧОтчет.Номенклатура Set end)

                // *** End programmer edit section *** (ТЧОтчет.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Avtomatizaciya_zakupok5.ОтчеЗакупках.
        /// </summary>
        // *** Start programmer edit section *** (ТЧОтчет.ОтчеЗакупках CustomAttributes)

        // *** End programmer edit section *** (ТЧОтчет.ОтчеЗакупках CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage("ОтчеЗакупках")]
        [TypeUsage(new string[] {
                "IIS.Avtomatizaciya_zakupok5.ЗаказПост",
                "IIS.Avtomatizaciya_zakupok5.ОтчеЗакупках"})]
        public virtual IIS.Avtomatizaciya_zakupok5.ОтчеЗакупках ОтчеЗакупках
        {
            get
            {
                // *** Start programmer edit section *** (ТЧОтчет.ОтчеЗакупках Get start)

                // *** End programmer edit section *** (ТЧОтчет.ОтчеЗакупках Get start)
                IIS.Avtomatizaciya_zakupok5.ОтчеЗакупках result = this.fОтчеЗакупках;
                // *** Start programmer edit section *** (ТЧОтчет.ОтчеЗакупках Get end)

                // *** End programmer edit section *** (ТЧОтчет.ОтчеЗакупках Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧОтчет.ОтчеЗакупках Set start)

                // *** End programmer edit section *** (ТЧОтчет.ОтчеЗакупках Set start)
                this.fОтчеЗакупках = value;
                // *** Start programmer edit section *** (ТЧОтчет.ОтчеЗакупках Set end)

                // *** End programmer edit section *** (ТЧОтчет.ОтчеЗакупках Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧОтчет.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧОтчет CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧОтчет CustomAttributes)
    public class DetailArrayOfТЧОтчет : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Avtomatizaciya_zakupok5.DetailArrayOfТЧОтчет members)

        // *** End programmer edit section *** (IIS.Avtomatizaciya_zakupok5.DetailArrayOfТЧОтчет members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧОтчет by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧОтчет.
        /// </summary>
        public DetailArrayOfТЧОтчет(IIS.Avtomatizaciya_zakupok5.ОтчеЗакупках fОтчеЗакупках) : 
                base(typeof(ТЧОтчет), ((ICSSoft.STORMNET.DataObject)(fОтчеЗакупках)))
        {
        }
        
        public IIS.Avtomatizaciya_zakupok5.ТЧОтчет this[int index]
        {
            get
            {
                return ((IIS.Avtomatizaciya_zakupok5.ТЧОтчет)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Avtomatizaciya_zakupok5.ТЧОтчет dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
